# Lines configured by zsh-newuser-install
HISTFILE=~/.zhistory
HISTSIZE=5000
SAVEHIST=5000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle :compinstall filename '/Users/felipe/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Ruby
source /usr/local/share/chruby/chruby.sh

# Antigen
source $(brew --prefix)/share/antigen/antigen.zsh
antigen theme steeef
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions
antigen apply

# History Substring Search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Editor
export EDITOR=emacs

# Node
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
