# Lines configured by zsh-newuser-install
HISTFILE=~/.zhistory
HISTSIZE=5000
SAVEHIST=5000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle :compinstall filename '/Users/felipe/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Terminal
export LANG=en_US.UTF-8

# Path
export PATH=$HOME/.local/bin:$PATH
export PATH=$(brew --prefix)/sbin:$PATH
export PATH=$HOME/dotfiles/git/bin:$PATH

# Ruby
if [ ! -f $(brew --prefix)/share/chruby/chruby.sh ]; then
    brew install chruby
fi

source $(brew --prefix)/share/chruby/chruby.sh
source $(brew --prefix)/share/chruby/auto.sh

# Antigen
if [ ! -f $(brew --prefix)/share/antigen/antigen.zsh ]; then
    brew install antigen
fi

source $(brew --prefix)/share/antigen/antigen.zsh
antigen theme steeef
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions
antigen apply

# History Substring Search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Editor
export EDITOR=emacs

# Node
if [ ! -f $(brew --prefix)/opt/nvm/nvm.sh ]; then
    brew install nvm
fi

export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix)/opt/nvm/nvm.sh"
