(set-keyboard-coding-system nil)
(global-linum-mode t) ;; Show line numbers
(setq column-number-mode t) ;; Show column numbers

;; Package system initialization
(require 'package)

(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)

(when (< emacs-major-version 24)
    (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))

(package-initialize)

;; Theming
(if (display-graphic-p)
    (load-theme 'solarized-dark t))

;; Package selection.
;; Autogenerated.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("afbb40954f67924d3153f27b6d3399df221b2050f2a72eb2cfa8d29ca783c5a8" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" default)))
 '(package-selected-packages
   (quote
    (editorconfig swift-mode solarized-theme dash-functional company-irony-c-headers))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;; Default font
(add-to-list 'default-frame-alist
	     '(font . "Inconsolata"))

;; Company
(require 'company)
(global-set-key (kbd "C-c SPC") 'company-complete)
(add-hook 'after-init-hook 'global-company-mode)

